// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SemanticCatalog.Persistence;

#nullable disable

namespace SemanticCatalog.Persistence.Migrations
{
    [DbContext(typeof(SemanticCatalogDbContext))]
    [Migration("20261001183321_InitialSemanticCatalog")]
    partial class InitialSemanticCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("semantic")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SemanticCatalog.Domain.CatalogFieldDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("config")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("object_type");

                    b.Property<string>("OwnerContext")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("owner_context");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("field_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_field_definitions");

                    b.HasIndex("TenantId", "OwnerContext", "ObjectType", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_field_definitions_tenant_id_owner_context_object_type_key");

                    b.ToTable("field_definitions", "semantic", t =>
                        {
                            t.HasCheckConstraint("ck_field_definitions_config_object", "jsonb_typeof(config) = 'object'");

                            t.HasCheckConstraint("ck_field_definitions_field_type", "field_type IN ('text','long_text','number','decimal','boolean','date','select','multi_select','email','phone','url')");

                            t.HasCheckConstraint("ck_field_definitions_key", "key ~ '^[a-z][a-z0-9_]{1,62}$'");

                            t.HasCheckConstraint("ck_field_definitions_owner", "owner_context = 'crm' AND object_type = 'opportunity'");

                            t.HasCheckConstraint("ck_field_definitions_sort_order", "sort_order BETWEEN 0 AND 10000");

                            t.HasCheckConstraint("ck_field_definitions_status", "status IN ('Active','Deprecated')");
                        });
                });

            modelBuilder.Entity("SemanticCatalog.Evidence.EvidenceRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<long>("AggregateId")
                        .HasColumnType("bigint")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_type");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("aggregate_version");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PrincipalIssuer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("principal_issuer");

                    b.Property<string>("PrincipalSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("principal_subject");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_evidence_records");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_evidence_records_correlation_id");

                    b.HasIndex("TenantId", "AggregateType", "AggregateId")
                        .HasDatabaseName("ix_evidence_records_tenant_id_aggregate_type_aggregate_id");

                    b.ToTable("evidence_records", "semantic");
                });

            modelBuilder.Entity("SemanticCatalog.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("PrincipalIssuer")
                        .HasColumnType("text")
                        .HasColumnName("principal_issuer");

                    b.Property<string>("PrincipalSubject")
                        .HasColumnType("text")
                        .HasColumnName("principal_subject");

                    b.Property<string>("Operation")
                        .HasColumnType("text")
                        .HasColumnName("operation");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponsePayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_payload");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("integer")
                        .HasColumnName("response_status");

                    b.HasKey("TenantId", "PrincipalIssuer", "PrincipalSubject", "Operation", "IdempotencyKey")
                        .HasName("pk_idempotency_records");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_records_expires_at");

                    b.ToTable("idempotency_records", "semantic");
                });

            modelBuilder.Entity("SemanticCatalog.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AggregateId")
                        .HasColumnType("bigint")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_type");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("aggregate_version");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid")
                        .HasColumnName("causation_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_messages_event_id");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at")
                        .HasFilter("processed_at IS NULL");

                    b.HasIndex("TenantId", "AggregateType", "AggregateId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id_aggregate_type_aggregate_id");

                    b.ToTable("outbox_messages", "semantic");
                });
#pragma warning restore 612, 618
        }
    }
}
