// <auto-generated />
using System;
using Collaboration.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Collaboration.Persistence.Migrations
{
    [DbContext(typeof(CollaborationDbContext))]
    partial class CollaborationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("collaboration")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Collaboration.Domain.CalendarEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllDay")
                        .HasColumnType("boolean")
                        .HasColumnName("all_day");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character(7)")
                        .HasColumnName("color")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("LinkBoundedContext")
                        .HasColumnType("text")
                        .HasColumnName("link_bounded_context");

                    b.Property<long?>("LinkEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("link_entity_id");

                    b.Property<string>("LinkEntityType")
                        .HasColumnType("text")
                        .HasColumnName("link_entity_type");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OwnerPrincipalIssuer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_principal_issuer");

                    b.Property<string>("OwnerPrincipalSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_principal_subject");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_calendar_entries");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_calendar_entries_tenant_id_id");

                    b.HasIndex("TenantId", "OwnerPrincipalIssuer", "OwnerPrincipalSubject", "Id")
                        .HasDatabaseName("ix_calendar_entries_owner_id");

                    b.HasIndex("TenantId", "OwnerPrincipalIssuer", "OwnerPrincipalSubject", "StartAt")
                        .HasDatabaseName("ix_calendar_entries_tenant_id_owner_principal_issuer_owner_pri");

                    b.HasIndex("TenantId", "OwnerPrincipalIssuer", "OwnerPrincipalSubject", "StartDate")
                        .HasDatabaseName("ix_calendar_entries_tenant_id_owner_principal_issuer_owner_pri1");

                    b.ToTable("calendar_entries", "collaboration", t =>
                        {
                            t.HasCheckConstraint("ck_calendar_entries_all_day_timing", "(all_day AND start_date IS NOT NULL AND end_date IS NOT NULL AND start_at IS NULL AND end_at IS NULL) OR (NOT all_day AND start_at IS NOT NULL AND start_date IS NULL AND end_date IS NULL)");

                            t.HasCheckConstraint("ck_calendar_entries_color", "color ~ '^#[0-9a-f]{6}$'");

                            t.HasCheckConstraint("ck_calendar_entries_end_at", "end_at IS NULL OR end_at > start_at");

                            t.HasCheckConstraint("ck_calendar_entries_end_date", "end_date IS NULL OR end_date > start_date");

                            t.HasCheckConstraint("ck_calendar_entries_link", "(link_bounded_context IS NULL AND link_entity_type IS NULL AND link_entity_id IS NULL) OR (link_bounded_context IS NOT NULL AND link_entity_type IS NOT NULL AND link_entity_id > 0)");

                            t.HasCheckConstraint("ck_calendar_entries_link_identifiers", "(link_bounded_context IS NULL OR link_bounded_context ~ '^[a-z][a-z0-9_]*$') AND (link_entity_type IS NULL OR link_entity_type ~ '^[a-z][a-z0-9_]*$')");

                            t.HasCheckConstraint("ck_calendar_entries_notes", "notes IS NULL OR char_length(notes) <= 4000");

                            t.HasCheckConstraint("ck_calendar_entries_title", "title = btrim(title) AND char_length(title) BETWEEN 1 AND 200 AND position(E'\\n' IN title) = 0 AND position(E'\\r' IN title) = 0");
                        });
                });

            modelBuilder.Entity("Collaboration.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("PrincipalIssuer")
                        .HasColumnType("text")
                        .HasColumnName("principal_issuer");

                    b.Property<string>("PrincipalSubject")
                        .HasColumnType("text")
                        .HasColumnName("principal_subject");

                    b.Property<string>("Operation")
                        .HasColumnType("text")
                        .HasColumnName("operation");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponsePayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_payload");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("integer")
                        .HasColumnName("response_status");

                    b.HasKey("TenantId", "PrincipalIssuer", "PrincipalSubject", "Operation", "IdempotencyKey")
                        .HasName("pk_idempotency_records");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_records_expires_at");

                    b.ToTable("idempotency_records", "collaboration");
                });

            modelBuilder.Entity("Collaboration.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AggregateId")
                        .HasColumnType("bigint")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_type");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("aggregate_version");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_messages_event_id");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", "collaboration");
                });
#pragma warning restore 612, 618
        }
    }
}
