// <auto-generated />
using System;
using CRM.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRM.Persistence.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    [Migration("20260924084051_EnforceOpportunityStageVersionFk")]
    partial class EnforceOpportunityStageVersionFk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("crm")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CRM.Customization.TenantFieldDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("aggregate_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("field_type");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_field_definitions");

                    b.HasIndex("TenantId", "AggregateType", "FieldName")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_field_definitions_tenant_id_aggregate_type_field_name");

                    b.ToTable("tenant_field_definitions", "crm", t =>
                        {
                            t.HasCheckConstraint("ck_tenant_field_definitions_aggregate_type", "aggregate_type IN ('Party','Opportunity')");

                            t.HasCheckConstraint("ck_tenant_field_definitions_field_type", "field_type IN ('text','number','boolean','date')");
                        });
                });

            modelBuilder.Entity("CRM.Domain.CrmSettings", b =>
                {
                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("AssignmentPolicy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("assignment_policy");

                    b.Property<string>("DefaultAssignmentMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("default_assignment_mode");

                    b.Property<long?>("DefaultOpportunityTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("default_opportunity_type_id");

                    b.Property<long?>("DefaultPipelineDefinitionId")
                        .HasColumnType("bigint")
                        .HasColumnName("default_pipeline_definition_id");

                    b.Property<string>("DefaultPrincipalIssuer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("default_principal_issuer");

                    b.Property<string>("DefaultPrincipalSubject")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("default_principal_subject");

                    b.Property<long?>("DefaultTeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("default_team_id");

                    b.Property<long?>("DefaultTerritoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("default_territory_id");

                    b.Property<string>("OpportunityCreationMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("opportunity_creation_mode");

                    b.Property<bool>("RequireLostReason")
                        .HasColumnType("boolean")
                        .HasColumnName("require_lost_reason");

                    b.Property<bool>("RequireWonLine")
                        .HasColumnType("boolean")
                        .HasColumnName("require_won_line");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId")
                        .HasName("pk_crm_settings");

                    b.HasIndex("TenantId", "DefaultOpportunityTypeId")
                        .HasDatabaseName("ix_crm_settings_tenant_id_default_opportunity_type_id");

                    b.HasIndex("TenantId", "DefaultPipelineDefinitionId")
                        .HasDatabaseName("ix_crm_settings_tenant_id_default_pipeline_definition_id");

                    b.ToTable("crm_settings", "crm", t =>
                        {
                            t.HasCheckConstraint("ck_crm_settings_default_principal_pair", "(default_principal_issuer IS NULL AND default_principal_subject IS NULL) OR (default_principal_issuer IS NOT NULL AND default_principal_subject IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("CRM.Domain.CustomerNeed", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("numeric(19,2)")
                        .HasColumnName("average_price");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_customer_needs");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_customer_needs_tenant_id_id");

                    b.ToTable("customer_needs", "crm", t =>
                        {
                            t.HasCheckConstraint("ck_customer_needs_average_price_non_negative", "average_price >= 0");
                        });
                });

            modelBuilder.Entity("CRM.Domain.LostReason", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_lost_reasons");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_lost_reasons_tenant_id_id");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_lost_reasons_tenant_id_key");

                    b.ToTable("lost_reasons", "crm");
                });

            modelBuilder.Entity("CRM.Domain.Opportunity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AssignedPrincipalIssuer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assigned_principal_issuer");

                    b.Property<string>("AssignedPrincipalSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assigned_principal_subject");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("CustomFields")
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_fields");

                    b.Property<decimal>("EstimatedAmount")
                        .HasColumnType("numeric(19,2)")
                        .HasColumnName("estimated_amount");

                    b.Property<DateTimeOffset?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<DateTimeOffset?>("LostDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lost_date");

                    b.Property<string>("LostReason")
                        .HasColumnType("text")
                        .HasColumnName("lost_reason");

                    b.Property<DateTimeOffset?>("OpenedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_date");

                    b.Property<long?>("OpportunityTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("opportunity_type_id");

                    b.Property<long>("PartyRefPartyId")
                        .HasColumnType("bigint")
                        .HasColumnName("party_ref_party_id");

                    b.Property<long?>("PipelineDefinitionVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("pipeline_definition_version_id");

                    b.Property<long?>("PipelineStageId")
                        .HasColumnType("bigint")
                        .HasColumnName("pipeline_stage_id");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("total_amount");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("WonDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("won_date");

                    b.HasKey("Id")
                        .HasName("pk_opportunities");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_opportunities_tenant_id_id");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_opportunities_tenant_id_created_at");

                    b.HasIndex("TenantId", "OpportunityTypeId")
                        .HasDatabaseName("ix_opportunities_tenant_id_opportunity_type_id");

                    b.HasIndex("TenantId", "PartyRefPartyId")
                        .HasDatabaseName("ix_opportunities_tenant_id_party_ref_party_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_opportunities_tenant_id_status");

                    b.HasIndex("TenantId", "AssignedPrincipalIssuer", "AssignedPrincipalSubject")
                        .HasDatabaseName("ix_opportunities_tenant_assigned_principal");

                    b.HasIndex("TenantId", "PipelineDefinitionVersionId", "PipelineStageId")
                        .HasDatabaseName("ix_opportunities_tenant_id_pipeline_definition_version_id_pipe");

                    b.ToTable("opportunities", "crm", t =>
                        {
                            t.HasCheckConstraint("ck_opportunities_estimated_amount_non_negative", "estimated_amount >= 0");

                            t.HasCheckConstraint("ck_opportunities_expiry_required_once_open", "status NOT IN ('open','won') OR expiry_date IS NOT NULL");

                            t.HasCheckConstraint("ck_opportunities_lost_fields_required_once_lost", "status <> 'lost' OR (lost_date IS NOT NULL AND lost_reason IS NOT NULL)");

                            t.HasCheckConstraint("ck_opportunities_party_ref_party_id_positive", "party_ref_party_id > 0");

                            t.HasCheckConstraint("ck_opportunities_status", "status IN ('draft','open','won','lost')");

                            t.HasCheckConstraint("ck_opportunities_won_date_required_once_won", "status <> 'won' OR won_date IS NOT NULL");
                        });
                });

            modelBuilder.Entity("CRM.Domain.OpportunityLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CancelReason")
                        .HasColumnType("text")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsCanceled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_canceled");

                    b.Property<bool>("IsOptional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_optional");

                    b.Property<decimal?>("LineTotal")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("line_total");

                    b.Property<long>("OpportunityId")
                        .HasColumnType("bigint")
                        .HasColumnName("opportunity_id");

                    b.Property<string>("ProductRefBoundedContext")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_ref_bounded_context");

                    b.Property<string>("ProductRefEntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_ref_entity_type");

                    b.Property<long>("ProductRefId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_ref_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(19,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_opportunity_lines");

                    b.HasIndex("TenantId", "OpportunityId")
                        .HasDatabaseName("ix_opportunity_lines_tenant_id_opportunity_id");

                    b.ToTable("opportunity_lines", "crm", t =>
                        {
                            t.HasCheckConstraint("ck_opportunity_lines_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("ck_opportunity_lines_unit_price_non_negative", "unit_price >= 0");
                        });
                });

            modelBuilder.Entity("CRM.Domain.OpportunityNeed", b =>
                {
                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<long>("OpportunityId")
                        .HasColumnType("bigint")
                        .HasColumnName("opportunity_id");

                    b.Property<long>("CustomerNeedId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_need_id");

                    b.HasKey("TenantId", "OpportunityId", "CustomerNeedId")
                        .HasName("pk_opportunity_needs");

                    b.HasIndex("TenantId", "CustomerNeedId")
                        .HasDatabaseName("ix_opportunity_needs_tenant_id_customer_need_id");

                    b.ToTable("opportunity_needs", "crm");
                });

            modelBuilder.Entity("CRM.Domain.OpportunityType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_opportunity_types");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_opportunity_types_tenant_id_id");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_opportunity_types_tenant_id_key");

                    b.ToTable("opportunity_types", "crm");
                });

            modelBuilder.Entity("CRM.Domain.PipelineDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_pipeline_definitions");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_pipeline_definitions_tenant_id_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_pipeline_definitions_tenant_id_name");

                    b.ToTable("pipeline_definitions", "crm");
                });

            modelBuilder.Entity("CRM.Domain.PipelineDefinitionVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("EnforceAllowedTransitions")
                        .HasColumnType("boolean")
                        .HasColumnName("enforce_allowed_transitions");

                    b.Property<long>("PipelineDefinitionId")
                        .HasColumnType("bigint")
                        .HasColumnName("pipeline_definition_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Published")
                        .HasColumnName("status");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_pipeline_definition_versions");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_pipeline_definition_versions_tenant_id_id");

                    b.HasIndex("TenantId", "PipelineDefinitionId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_pipeline_definition_versions_tenant_id_pipeline_definition_");

                    b.ToTable("pipeline_definition_versions", "crm");
                });

            modelBuilder.Entity("CRM.Domain.PipelineStage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsEntry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_entry");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("PipelineDefinitionVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("pipeline_definition_version_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_pipeline_stages");

                    b.HasAlternateKey("TenantId", "PipelineDefinitionVersionId", "Id")
                        .HasName("ak_pipeline_stages_tenant_id_pipeline_definition_version_id_id");

                    b.HasIndex("TenantId", "PipelineDefinitionVersionId")
                        .IsUnique()
                        .HasDatabaseName("ux_pipeline_stages_one_entry_per_version")
                        .HasFilter("is_entry = true");

                    b.HasIndex("TenantId", "PipelineDefinitionVersionId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_pipeline_stages_tenant_id_pipeline_definition_version_id_na");

                    b.HasIndex("TenantId", "PipelineDefinitionVersionId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("ix_pipeline_stages_tenant_id_pipeline_definition_version_id_so");

                    b.ToTable("pipeline_stages", "crm");
                });

            modelBuilder.Entity("CRM.Domain.PipelineStageTransition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FromStageId")
                        .HasColumnType("bigint")
                        .HasColumnName("from_stage_id");

                    b.Property<long>("PipelineDefinitionVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("pipeline_definition_version_id");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<long>("ToStageId")
                        .HasColumnType("bigint")
                        .HasColumnName("to_stage_id");

                    b.HasKey("Id")
                        .HasName("pk_pipeline_stage_transitions");

                    b.HasIndex("TenantId", "PipelineDefinitionVersionId", "ToStageId")
                        .HasDatabaseName("ix_pipeline_stage_transitions_tenant_id_pipeline_definition_ve");

                    b.HasIndex("TenantId", "PipelineDefinitionVersionId", "FromStageId", "ToStageId")
                        .IsUnique()
                        .HasDatabaseName("ix_pipeline_stage_transitions_tenant_id_pipeline_definition_ve1");

                    b.ToTable("pipeline_stage_transitions", "crm");
                });

            modelBuilder.Entity("CRM.Evidence.EvidenceRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<long>("AggregateId")
                        .HasColumnType("bigint")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_type");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("aggregate_version");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PrincipalIssuer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("principal_issuer");

                    b.Property<string>("PrincipalSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("principal_subject");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_evidence_records");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_evidence_records_correlation_id");

                    b.HasIndex("TenantId", "AggregateType", "AggregateId")
                        .HasDatabaseName("ix_evidence_records_tenant_id_aggregate_type_aggregate_id");

                    b.ToTable("evidence_records", "crm");
                });

            modelBuilder.Entity("CRM.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("PrincipalIssuer")
                        .HasColumnType("text")
                        .HasColumnName("principal_issuer");

                    b.Property<string>("PrincipalSubject")
                        .HasColumnType("text")
                        .HasColumnName("principal_subject");

                    b.Property<string>("Operation")
                        .HasColumnType("text")
                        .HasColumnName("operation");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponsePayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_payload");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("integer")
                        .HasColumnName("response_status");

                    b.HasKey("TenantId", "PrincipalIssuer", "PrincipalSubject", "Operation", "IdempotencyKey")
                        .HasName("pk_idempotency_records");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_records_expires_at");

                    b.ToTable("idempotency_records", "crm");
                });

            modelBuilder.Entity("CRM.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AggregateId")
                        .HasColumnType("bigint")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_type");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("aggregate_version");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid")
                        .HasColumnName("causation_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_messages_event_id");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at")
                        .HasFilter("processed_at IS NULL");

                    b.HasIndex("TenantId", "AggregateType", "AggregateId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id_aggregate_type_aggregate_id");

                    b.ToTable("outbox_messages", "crm");
                });

            modelBuilder.Entity("CRM.Domain.CrmSettings", b =>
                {
                    b.HasOne("CRM.Domain.OpportunityType", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "DefaultOpportunityTypeId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_crm_settings_opportunity_types_tenant_id_default_opportunit");

                    b.HasOne("CRM.Domain.PipelineDefinition", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "DefaultPipelineDefinitionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_crm_settings_pipeline_definitions_tenant_id_default_pipelin");
                });

            modelBuilder.Entity("CRM.Domain.Opportunity", b =>
                {
                    b.HasOne("CRM.Domain.OpportunityType", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OpportunityTypeId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_opportunities_opportunity_types_tenant_id_opportunity_type_");

                    b.HasOne("CRM.Domain.PipelineDefinitionVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PipelineDefinitionVersionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_opportunities_pipeline_definition_versions_tenant_id_pipeli");

                    b.HasOne("CRM.Domain.PipelineStage", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PipelineDefinitionVersionId", "PipelineStageId")
                        .HasPrincipalKey("TenantId", "PipelineDefinitionVersionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_opportunities_pipeline_stages_tenant_id_pipeline_definition");
                });

            modelBuilder.Entity("CRM.Domain.OpportunityLine", b =>
                {
                    b.HasOne("CRM.Domain.Opportunity", null)
                        .WithMany("Lines")
                        .HasForeignKey("TenantId", "OpportunityId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_opportunity_lines_opportunities_tenant_id_opportunity_id");
                });

            modelBuilder.Entity("CRM.Domain.OpportunityNeed", b =>
                {
                    b.HasOne("CRM.Domain.CustomerNeed", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CustomerNeedId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_opportunity_needs_customer_needs_tenant_id_customer_need_id");

                    b.HasOne("CRM.Domain.Opportunity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OpportunityId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_opportunity_needs_opportunities_tenant_id_opportunity_id");
                });

            modelBuilder.Entity("CRM.Domain.PipelineDefinitionVersion", b =>
                {
                    b.HasOne("CRM.Domain.PipelineDefinition", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PipelineDefinitionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pipeline_definition_versions_pipeline_definitions_tenant_id");
                });

            modelBuilder.Entity("CRM.Domain.PipelineStage", b =>
                {
                    b.HasOne("CRM.Domain.PipelineDefinitionVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PipelineDefinitionVersionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pipeline_stages_pipeline_definition_versions_tenant_id_pipe");
                });

            modelBuilder.Entity("CRM.Domain.PipelineStageTransition", b =>
                {
                    b.HasOne("CRM.Domain.PipelineDefinitionVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PipelineDefinitionVersionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pipeline_stage_transitions_pipeline_definition_versions_ten");

                    b.HasOne("CRM.Domain.PipelineStage", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PipelineDefinitionVersionId", "FromStageId")
                        .HasPrincipalKey("TenantId", "PipelineDefinitionVersionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pipeline_stage_transitions_pipeline_stages_tenant_id_pipeli");

                    b.HasOne("CRM.Domain.PipelineStage", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PipelineDefinitionVersionId", "ToStageId")
                        .HasPrincipalKey("TenantId", "PipelineDefinitionVersionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pipeline_stage_transitions_pipeline_stages_tenant_id_pipeli1");
                });

            modelBuilder.Entity("CRM.Domain.Opportunity", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
