// <auto-generated />
using System;
using Access.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Access.Persistence.Migrations
{
    [DbContext(typeof(AccessDbContext))]
    partial class AccessDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Access.Domain.Authentication.AccountCredential", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempts");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("LoginEmailNormalized")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("login_email_normalized");

                    b.Property<DateTimeOffset>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.HasKey("AccountId")
                        .HasName("pk_account_credentials");

                    b.HasIndex("LoginEmailNormalized")
                        .IsUnique()
                        .HasDatabaseName("ix_account_credentials_login_email_normalized_unique");

                    b.ToTable("account_credentials", "identity");
                });

            modelBuilder.Entity("Access.Domain.Authentication.AccountToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("EmailNormalized")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email_normalized");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Locale")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("locale");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("purpose");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_account_tokens");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_account_tokens_account_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_account_tokens_token_hash_unique");

                    b.HasIndex("EmailNormalized", "TenantId")
                        .HasDatabaseName("ix_account_tokens_outstanding_invites")
                        .HasFilter("purpose = 'invite' AND consumed_at IS NULL AND revoked_at IS NULL");

                    b.ToTable("account_tokens", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_account_tokens_account_purposes_have_account", "purpose = 'invite' OR account_id IS NOT NULL");

                            t.HasCheckConstraint("ck_account_tokens_invite_shape", "purpose <> 'invite' OR (tenant_id IS NOT NULL AND email_normalized IS NOT NULL)");

                            t.HasCheckConstraint("ck_account_tokens_purpose", "purpose IN ('invite', 'password_reset', 'password_setup')");
                        });
                });

            modelBuilder.Entity("Access.Domain.Authentication.AuthEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Detail")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<string>("IpHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ip_hash");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("outcome");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_events");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_auth_events_account_id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_auth_events_correlation_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_auth_events_occurred_at");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_auth_events_session_id");

                    b.ToTable("auth_events", "identity");
                });

            modelBuilder.Entity("Access.Domain.Authentication.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("absolute_expires_at");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<long?>("ActiveTenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("active_tenant_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("revoked_reason");

                    b.Property<string>("UserAgentHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_agent_hash");

                    b.HasKey("Id")
                        .HasName("pk_auth_sessions");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_auth_sessions_account_id");

                    b.HasIndex("AccountId", "CreatedAt")
                        .HasDatabaseName("ix_auth_sessions_account_id_created_at");

                    b.ToTable("auth_sessions", "identity");
                });

            modelBuilder.Entity("Access.Domain.Authentication.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_id");

                    b.Property<DateTimeOffset?>("RotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rotated_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_auth_refresh_tokens");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_auth_refresh_tokens_session_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_auth_refresh_tokens_token_hash_unique");

                    b.ToTable("auth_refresh_tokens", "identity");
                });

            modelBuilder.Entity("Access.Domain.Authorization.ActionRegistryEntry", b =>
                {
                    b.Property<string>("ActionKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("action_key");

                    b.Property<bool>("IsDeprecated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deprecated");

                    b.Property<string>("OwnerModule")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_module");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resource_type");

                    b.Property<string>("RiskClass")
                        .HasColumnType("text")
                        .HasColumnName("risk_class");

                    b.HasKey("ActionKey")
                        .HasName("pk_actions");

                    b.ToTable("actions", "access");
                });

            modelBuilder.Entity("Access.Domain.Authorization.PermissionSet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origin");

                    b.Property<string>("OriginModuleKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("origin_module_key");

                    b.Property<int?>("OriginVersion")
                        .HasColumnType("integer")
                        .HasColumnName("origin_version");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_permission_sets");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_permission_sets_tenant_id_id");

                    b.HasIndex("TenantId", "Id")
                        .IsUnique()
                        .HasDatabaseName("ix_permission_sets_tenant_id_id");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_permission_sets_tenant_id_key");

                    b.ToTable("permission_sets", "access", t =>
                        {
                            t.HasCheckConstraint("ck_permission_sets_origin", "origin IN ('tenant','system_template')");

                            t.HasCheckConstraint("ck_permission_sets_provenance", "(origin_module_key IS NULL) = (origin_version IS NULL) AND (origin_module_key IS NULL OR origin = 'system_template') AND (origin_version IS NULL OR origin_version >= 1)");
                        });
                });

            modelBuilder.Entity("Access.Domain.Authorization.PermissionSetItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionKey")
                        .IsRequired()
                        .HasColumnType("character varying(200)")
                        .HasColumnName("action_key");

                    b.Property<long>("PermissionSetId")
                        .HasColumnType("bigint")
                        .HasColumnName("permission_set_id");

                    b.Property<string>("Relation")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("relation");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_permission_set_items");

                    b.HasIndex("ActionKey")
                        .HasDatabaseName("ix_permission_set_items_action_key");

                    b.HasIndex("TenantId", "ActionKey")
                        .HasDatabaseName("ix_permission_set_items_tenant_id_action_key");

                    b.HasIndex("TenantId", "PermissionSetId")
                        .HasDatabaseName("ix_permission_set_items_tenant_id_permission_set_id");

                    b.ToTable("permission_set_items", "access", t =>
                        {
                            t.HasCheckConstraint("ck_permission_set_items_relation", "relation IS NULL OR relation = 'owner'");
                        });
                });

            modelBuilder.Entity("Access.Domain.Authorization.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origin");

                    b.Property<string>("OriginModuleKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("origin_module_key");

                    b.Property<int?>("OriginVersion")
                        .HasColumnType("integer")
                        .HasColumnName("origin_version");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_roles_tenant_id_id");

                    b.HasIndex("TenantId", "Id")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_tenant_id_id");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_tenant_id_key");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_tenant_id_name");

                    b.ToTable("roles", "access", t =>
                        {
                            t.HasCheckConstraint("ck_roles_origin", "origin IN ('tenant','system_template')");

                            t.HasCheckConstraint("ck_roles_provenance", "(origin_module_key IS NULL) = (origin_version IS NULL) AND (origin_module_key IS NULL OR origin = 'system_template') AND (origin_version IS NULL OR origin_version >= 1)");
                        });
                });

            modelBuilder.Entity("Access.Domain.Authorization.RoleAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<long>("GrantedByAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("granted_by_account_id");

                    b.Property<string>("PrincipalType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("principal_type");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("source");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_role_assignments");

                    b.HasIndex("TenantId", "AccountId")
                        .HasDatabaseName("ix_role_assignments_tenant_id_account_id");

                    b.HasIndex("TenantId", "RoleId")
                        .HasDatabaseName("ix_role_assignments_tenant_id_role_id");

                    b.ToTable("role_assignments", "access", t =>
                        {
                            t.HasCheckConstraint("ck_role_assignments_principal_type", "principal_type = 'user'");

                            t.HasCheckConstraint("ck_role_assignments_source", "source IN ('manual','bootstrap','module_enablement')");

                            t.HasCheckConstraint("ck_role_assignments_valid_range", "valid_to IS NULL OR valid_to > valid_from");
                        });
                });

            modelBuilder.Entity("Access.Domain.Authorization.RolePermissionSet", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<long>("PermissionSetId")
                        .HasColumnType("bigint")
                        .HasColumnName("permission_set_id");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("RoleId", "PermissionSetId")
                        .HasName("pk_role_permission_sets");

                    b.HasIndex("TenantId", "PermissionSetId")
                        .HasDatabaseName("ix_role_permission_sets_tenant_id_permission_set_id");

                    b.HasIndex("TenantId", "RoleId")
                        .HasDatabaseName("ix_role_permission_sets_tenant_id_role_id");

                    b.ToTable("role_permission_sets", "access");
                });

            modelBuilder.Entity("Access.Domain.Authorization.TenantAccessState", b =>
                {
                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("revision");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.HasKey("TenantId")
                        .HasName("pk_tenant_access_state");

                    b.ToTable("tenant_access_state", "access");
                });

            modelBuilder.Entity("Access.Domain.Authorization.TenantModuleEnablement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("EnabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enabled_at");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("module_key");

                    b.Property<int>("TemplateVersion")
                        .HasColumnType("integer")
                        .HasColumnName("template_version");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_module_enablements");

                    b.HasIndex("TenantId", "ModuleKey")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_module_enablements_tenant_id_module_key");

                    b.ToTable("tenant_module_enablements", "access", t =>
                        {
                            t.HasCheckConstraint("ck_tenant_module_enablements_version", "template_version >= 1");
                        });
                });

            modelBuilder.Entity("Access.Domain.Identity.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Locale")
                        .HasColumnType("text")
                        .HasColumnName("locale");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.ToTable("accounts", "identity");
                });

            modelBuilder.Entity("Access.Domain.Identity.ExternalIdentity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issuer");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.Property<string>("RawClaims")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_claims");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("pk_external_identities");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_external_identities_account_id");

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ix_external_identities_issuer_subject");

                    b.ToTable("external_identities", "identity");
                });

            modelBuilder.Entity("Access.Domain.Identity.TenantMembership", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<DateTimeOffset>("InvitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invited_at");

                    b.Property<DateTimeOffset?>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_memberships");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_tenant_memberships_account_id");

                    b.HasIndex("TenantId", "AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_memberships_tenant_id_account_id");

                    b.ToTable("tenant_memberships", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_tenant_memberships_status", "status IN ('invited','active','disabled')");
                        });
                });

            modelBuilder.Entity("Access.Evidence.EvidenceRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<long>("AggregateId")
                        .HasColumnType("bigint")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_type");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("aggregate_version");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PrincipalIssuer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("principal_issuer");

                    b.Property<string>("PrincipalSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("principal_subject");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_evidence_records");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_evidence_records_correlation_id");

                    b.HasIndex("TenantId", "AggregateType", "AggregateId")
                        .HasDatabaseName("ix_evidence_records_tenant_id_aggregate_type_aggregate_id");

                    b.ToTable("evidence_records", "access");
                });

            modelBuilder.Entity("Access.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("PrincipalIssuer")
                        .HasColumnType("text")
                        .HasColumnName("principal_issuer");

                    b.Property<string>("PrincipalSubject")
                        .HasColumnType("text")
                        .HasColumnName("principal_subject");

                    b.Property<string>("Operation")
                        .HasColumnType("text")
                        .HasColumnName("operation");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponsePayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_payload");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("integer")
                        .HasColumnName("response_status");

                    b.HasKey("TenantId", "PrincipalIssuer", "PrincipalSubject", "Operation", "IdempotencyKey")
                        .HasName("pk_idempotency_records");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_records_expires_at");

                    b.ToTable("idempotency_records", "access");
                });

            modelBuilder.Entity("Access.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AggregateId")
                        .HasColumnType("bigint")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_type");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("aggregate_version");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid")
                        .HasColumnName("causation_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_messages_event_id");

                    b.HasIndex("TenantId", "ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_tenant_id_processed_at");

                    b.ToTable("outbox_messages", "access");
                });

            modelBuilder.Entity("Access.Domain.Authentication.AccountCredential", b =>
                {
                    b.HasOne("Access.Domain.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_credentials_accounts_account_id");
                });

            modelBuilder.Entity("Access.Domain.Authentication.AccountToken", b =>
                {
                    b.HasOne("Access.Domain.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_account_tokens_accounts_account_id");
                });

            modelBuilder.Entity("Access.Domain.Authentication.AuthSession", b =>
                {
                    b.HasOne("Access.Domain.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_sessions_accounts_account_id");
                });

            modelBuilder.Entity("Access.Domain.Authentication.RefreshToken", b =>
                {
                    b.HasOne("Access.Domain.Authentication.AuthSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_refresh_tokens_auth_sessions_session_id");
                });

            modelBuilder.Entity("Access.Domain.Authorization.PermissionSetItem", b =>
                {
                    b.HasOne("Access.Domain.Authorization.ActionRegistryEntry", null)
                        .WithMany()
                        .HasForeignKey("ActionKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_permission_set_items_actions_action_key");

                    b.HasOne("Access.Domain.Authorization.PermissionSet", null)
                        .WithMany("Items")
                        .HasForeignKey("TenantId", "PermissionSetId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_permission_set_items_permission_sets_tenant_id_permission_s");
                });

            modelBuilder.Entity("Access.Domain.Authorization.RoleAssignment", b =>
                {
                    b.HasOne("Access.Domain.Authorization.Role", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RoleId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_assignments_roles_tenant_id_role_id");
                });

            modelBuilder.Entity("Access.Domain.Authorization.RolePermissionSet", b =>
                {
                    b.HasOne("Access.Domain.Authorization.PermissionSet", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PermissionSetId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permission_sets_permission_sets_tenant_id_permission_s");

                    b.HasOne("Access.Domain.Authorization.Role", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RoleId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permission_sets_roles_tenant_id_role_id");
                });

            modelBuilder.Entity("Access.Domain.Identity.ExternalIdentity", b =>
                {
                    b.HasOne("Access.Domain.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_identities_accounts_account_id");
                });

            modelBuilder.Entity("Access.Domain.Identity.TenantMembership", b =>
                {
                    b.HasOne("Access.Domain.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_memberships_accounts_account_id");
                });

            modelBuilder.Entity("Access.Domain.Authorization.PermissionSet", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
