<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Contracts\Contracts.csproj" />
    <ProjectReference Include="..\Modules\TenantLifecycle\TenantLifecycle.csproj" />
    <ProjectReference Include="..\Modules\Access\Access.csproj" />
    <ProjectReference Include="..\Modules\Organization\Organization.csproj" />
    <ProjectReference Include="..\Modules\MasterData\MasterData.csproj" />
    <ProjectReference Include="..\Modules\CRM\CRM.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
