/** Every route string lives here so links and guards can never drift apart. */
export const paths = {
  login: '/login',
  selectTenant: '/select-tenant',
  noAccess: '/no-access',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  acceptInvite: '/accept-invite',
  register: '/register',
  accountSecurity: '/account/security',
  dashboard: '/dashboard',
  /** Legacy URLs, kept only so old links redirect to the current ones — see `routes/index.tsx`. */
  legacySettings: '/settings',
  pipeline: '/pipeline',
  pipelineDashboard: '/pipeline/dashboard',
  crmLegacyPipeline: '/crm/pipeline',
  crm: '/crm',
  crmDashboard: '/crm/dashboard',
  crmOpportunities: '/crm/opportunities',
  crmOpportunityNew: '/crm/opportunities/new',
  /** The react-router pattern; use `crmOpportunity(id)` to build a link. */
  crmOpportunityPattern: '/crm/opportunities/:id',
  crmOpportunity: (id: number) => `/crm/opportunities/${id}`,
  calendar: '/calendar',
  /** Opens the calendar's create dialog with a record already linked (`crm/opportunity/17`). Only `CalendarPage` reads it. */
  calendarWithLink: (boundedContext: string, entityType: string, id: number) =>
    `/calendar?link=${encodeURIComponent(`${boundedContext}/${entityType}/${id}`)}`,
  reports: '/reports',
  files: '/files',
  feedback: '/feedback',
  settings: '/profile/settings',
  companySettings: '/company/settings',
  members: '/members',
  demoTables: '/demo/tables',
  demoForms: '/demo/forms',
  demoCharts: '/demo/charts',
  demoOverlays: '/demo/overlays',
  demoNotifications: '/demo/notifications',
  demoStates: '/demo/states',
  demoDrawers: '/demo/drawers',
  demoKanban: '/demo/kanban',
  demoTimeline: '/demo/timeline',
  demoBadges: '/demo/badges',
  demoFilters: '/demo/filters',
} as const
