// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TenantLifecycle.Persistence;

#nullable disable

namespace TenantLifecycle.Persistence.Migrations
{
    [DbContext(typeof(TenantLifecycleDbContext))]
    [Migration("20260922081607_EnableRowLevelSecurity")]
    partial class EnableRowLevelSecurity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tenant_lifecycle")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TenantLifecycle.Domain.TenantProfile", b =>
                {
                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency_code")
                        .IsFixedLength();

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("LegalName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tax_number");

                    b.Property<string>("TaxOffice")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("tax_office");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId")
                        .HasName("pk_tenant_profiles");

                    b.ToTable("tenant_profiles", "tenant_lifecycle", t =>
                        {
                            t.HasCheckConstraint("ck_tenant_profiles_address", "address IS NULL OR (address = btrim(address) AND char_length(address) <= 500 AND address !~ '[\\u0001-\\u0009\\u000b-\\u001f\\u007f-\\u009f\\u2028\\u2029]')");

                            t.HasCheckConstraint("ck_tenant_profiles_currency_code", "currency_code ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_tenant_profiles_display_name", "btrim(display_name) = display_name AND display_name !~ '[\\u0001-\\u001f\\u007f-\\u009f\\u2028\\u2029]' AND char_length(display_name) BETWEEN 2 AND 120");

                            t.HasCheckConstraint("ck_tenant_profiles_email", "email IS NULL OR (email = btrim(email) AND email = lower(email) AND char_length(email) BETWEEN 1 AND 254)");

                            t.HasCheckConstraint("ck_tenant_profiles_legal_name", "legal_name IS NULL OR (btrim(legal_name) = legal_name AND legal_name !~ '[\\u0001-\\u001f\\u007f-\\u009f\\u2028\\u2029]' AND char_length(legal_name) BETWEEN 1 AND 160)");

                            t.HasCheckConstraint("ck_tenant_profiles_phone", "phone IS NULL OR (btrim(phone) = phone AND phone !~ '[\\u0001-\\u001f\\u007f-\\u009f\\u2028\\u2029]' AND char_length(phone) BETWEEN 1 AND 32)");

                            t.HasCheckConstraint("ck_tenant_profiles_tax_number", "tax_number IS NULL OR (btrim(tax_number) = tax_number AND tax_number !~ '[\\u0001-\\u001f\\u007f-\\u009f\\u2028\\u2029]' AND char_length(tax_number) BETWEEN 1 AND 32)");

                            t.HasCheckConstraint("ck_tenant_profiles_tax_office", "tax_office IS NULL OR (btrim(tax_office) = tax_office AND tax_office !~ '[\\u0001-\\u001f\\u007f-\\u009f\\u2028\\u2029]' AND char_length(tax_office) BETWEEN 1 AND 120)");

                            t.HasCheckConstraint("ck_tenant_profiles_tenant_id", "tenant_id > 0");

                            t.HasCheckConstraint("ck_tenant_profiles_timezone", "btrim(timezone) = timezone AND timezone !~ '[\\u0001-\\u001f\\u007f-\\u009f\\u2028\\u2029]' AND char_length(timezone) BETWEEN 1 AND 64");
                        });
                });

            modelBuilder.Entity("TenantLifecycle.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("PrincipalIssuer")
                        .HasColumnType("text")
                        .HasColumnName("principal_issuer");

                    b.Property<string>("PrincipalSubject")
                        .HasColumnType("text")
                        .HasColumnName("principal_subject");

                    b.Property<string>("Operation")
                        .HasColumnType("text")
                        .HasColumnName("operation");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponsePayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_payload");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("integer")
                        .HasColumnName("response_status");

                    b.HasKey("TenantId", "PrincipalIssuer", "PrincipalSubject", "Operation", "IdempotencyKey")
                        .HasName("pk_idempotency_records");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_records_expires_at");

                    b.ToTable("idempotency_records", "tenant_lifecycle");
                });

            modelBuilder.Entity("TenantLifecycle.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AggregateId")
                        .HasColumnType("bigint")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_type");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("aggregate_version");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid")
                        .HasColumnName("causation_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_messages_event_id");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at")
                        .HasFilter("processed_at IS NULL");

                    b.HasIndex("TenantId", "AggregateType", "AggregateId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id_aggregate_type_aggregate_id");

                    b.ToTable("outbox_messages", "tenant_lifecycle");
                });
#pragma warning restore 612, 618
        }
    }
}
