import {
  BarChart3,
  BadgeCheck,
  BookOpen,
  Bot,
  Boxes,
  Building2,
  Calendar,
  CheckSquare,
  ClipboardCheck,
  Columns3,
  Factory,
  FileText,
  Folder,
  Inbox,
  HandCoins,
  HardHat,
  Headset,
  Megaphone,
  MessagesSquare,
  NotebookPen,
  ShoppingCart,
  Truck,
  UsersRound,
  Warehouse,
  Wrench,
  Workflow,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import type { ApplicationIconKey } from './types'

export const APPLICATION_ICON: Record<ApplicationIconKey, LucideIcon> = {
  crm: Columns3,
  sales: FileText,
  marketing: Megaphone,
  service: Headset,
  purchasing: ShoppingCart,
  inventoryWarehouse: Warehouse,
  supplyChainPlanning: Truck,
  production: Factory,
  quality: BadgeCheck,
  assetMaintenance: Wrench,
  productPlm: Boxes,
  finance: HandCoins,
  projects: HardHat,
  humanResources: UsersRound,
  b2bCommerce: Building2,
  documentManagement: Folder,
  inbox: Inbox,
  calendar: Calendar,
  tasks: CheckSquare,
  conversations: MessagesSquare,
  notes: NotebookPen,
  files: Folder,
  knowledgeBase: BookOpen,
  approvals: ClipboardCheck,
  reportsAnalytics: BarChart3,
  automations: Workflow,
  aiCopilot: Bot,
}
